eureka:
  instance:
    hostname: @pom.artifactId@
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

spring:
  security:
    user:
      password: root
      name: root
